[pyprland]
plugins = [
   "scratchpads",
   # "layout_center",
   # "expose",
   # "system_notifier",
]


# [scratchpads.mattermost]
# command = "mattermost-desktop"
# class = "Mattermost"
# # unfocus = "hide"
# size = "96% 94%"
# position = "2% 2%"
# lazy = true


# [scratchpads.term]
# animation = "fromTop"
# command = "kitty --class kitty-dropterm"
# class = "kitty-dropterm"
# size = "75% 60%"
# max_size = "1920px 100%"
# margin = 50


# [scratchpads.warp1]
# command = "warp-terminal"
# class = "dev.warp.Warp"
# workspace = "special:scratch_warp1"
# size = "90% 80%"
# position = "5% 5%"

# [scratchpads.warp2]
# command = "warp-terminal"
# class = "dev.warp.Warp"
# workspace = "special:scratch_warp2"
# size = "90% 80%"
# position = "5% 5%"

# [scratchpads.term5]
# command = "alacritty --class term5"
# class = "term5"
# size = "50% 50%"
# position = "0% 0%"
# [scratchpads.term6]
# command = "alacritty --class term6"
# class = "term6"
# size = "50% 50%"
# position = "50% 0%"
# [scratchpads.term7]
# command = "alacritty --class term7"
# class = "term7"
# size = "50% 50%"
# position = "0% 50%"
# [scratchpads.term8]
# command = "alacritty --class term8"
# class = "term8"
# size = "50% 50%"
# position = "50% 50%"

# [scratchpads.term5]
# command = "alacritty --class scratchpad"
# class = "scratchpad"
# size = "75% 60%"
# position = "5% 10%"
# [scratchpads.term6]
# command = "alacritty --class scratchpad"
# class = "scratchpad"
# size = "75% 60%"
# position = "20% 10%"
# [scratchpads.term7]
# command = "alacritty --class scratchpad"
# class = "scratchpad"
# size = "75% 60%"
# position = "5% 30%"
# [scratchpads.term8]
# command = "alacritty --class scratchpad"
# class = "scratchpad"
# size = "75% 60%"
# position = "20% 30%"


# [scratchpads.sublkeys]
# command = "subl /home/sheffler/.config/sublime-text-3/Packages/User/ide/sublkeys.sublime-project"
# class = "scratchpad"
# lazy = true
# unfocus = "hide"
# size = "94% 94%"
# position = "5% 5%"
# [scratchpads.clipse]
# command = "alacritty --class clipse -e clipse"
# class = "clipse"
# size = "96% 94%"
# position = "2% 2%"
# [scratchpads.btop]
# command = "alacritty --class btop -e btop"
# class = "btop"
# size = "96% 94%"
# position = "2% 2%"
# [scratchpads.htop]
# command = "alacritty --class scratchpad -e htop"
# class = "scratchpad"
# size = "96% 94%"
# position = "2% 2%"
# [scratchpads.chatgpt]
# command = "qutebrowser -r chatgpt"
# class = "org.qutebrowser.qutebrowser"
# lazy = true
# unfocus = "hide"
# size = "96% 94%"
# position = "2% 2%"
#

#[scratchpads.config]
#command = "subl --project /home/sheffler/.local/share/chezmoi/ide/chezmoi.sublime-project"
#class = "sublime_text"
#size = "96% 94%"
#position = "2% 2%"
#lazy = true

# [scratchpads.zed]
# command = "zeditor --class=zed"
# class = "dev.zed.Zed"
# size = "96% 94%"
# position = "2% 2%"
# # lazy = true

# [scratchpads.chatgpt]
# command = "chat-gpt"
# class = "chat-gpt"
# size = "96% 94%"
# position = "2% 2%"
# lazy = true

# [scratchpads.cursor]
# command = "cursor"
# class = "Cursor"
# size = "96% 94%"
# position = "2% 2%"
# lazy = true

# [scratchpads.chrome]
# command = "google-chrome-stable --ozone-platform=wayland --class=chrome"
# class = "chrome"
# size = "96% 94%"
# position = "2% 2%"
# lazy = true
# [scratchpads.chromium]
# command = "chromium --ozone-platform=wayland"
# class = "chromium"
# size = "96% 94%"
# position = "2% 2%"
# lazy = true

# [scratchpads.music]
# command = "spotify"
# class = "Spotify"
# # unfocus = "hide"
# size = "96% 94%"
# position = "2% 2%"
# # lazy = true

# [scratchpads.smerge]
# command = "smerge --new-window"
# class = "smerge"
# size = "96% 94%"
# position = "2% 2%"
# lazy = true

# [scratchpads.waypaper]
# command = "waypaper"
# class = "waypaper"
# size = "94% 94%"
# position = "5% 5%"

# [scratchpads.thunar]
# command = "thunar"
# class = "thunar"
# lazy = true
# unfocus = "hide"
# size = "94% 94%"
# position = "5% 5%"

# [system_notifier.sources]
# command = "sudo journalctl -fx"
# parser = "journal"
# [system_notifier.parsers.journal]
# pattern = "([a-z0-9]+): Link UP$"
# filter = "s/.*\[\d+\]: ([a-z0-9]+): Link.*/\1 is active/"
# color= "#00aa00"
# [system_notifier.parsers.journal]
# pattern = "([a-z0-9]+): Link DOWN$"
# filter = "s/.*\[\d+\]: ([a-z0-9]+): Link.*/\1 is inactive/"
# color= "#ff8800"
# [system_notifier.parsers.journal]
# pattern = "Process \d+ \(.*\) of .* dumped core."
# filter = "s/.*Process \d+ \((.*)\) of .* dumped core./\1 dumped core/"
# color= "#aa0000"
# [system_notifier.parsers.journal]
# pattern = "usb \d+-[0-9.]+: Product: "
# filter = "s/.*usb \d+-[0-9.]+: Product: (.*)/USB plugged: \1/"
# [expose]
# include_special = false
# [layout_center]
# # margin = 60
# # offset = [30, 30]
# size = "60% 60%"
# position = "20% 20%"
# next = "movefocus r"
# prev = "movefocus l"
# next2 = "movefocus d"
# prev2 = "movefocus u"
