# windowrule = workspace 1, class:workspace1
# windowrule = workspace 3, title:(.*)(/mlb/)(.*)
# windowrule = workspace 3, title:(.*)(src/arctic_diamond/)(.*)
# windowrule = workspace 5, title:(.*)(/src/game_theory_thing_original_idea/)(.*)
# windowrule = workspace 9, title:(.*)Sublime Merge(.*)
# windowrule = workspace 0, title:(.*)Mattermost Desktop App(.*)

# windowrule=f-loat,title:(.*)(\(Linux\)\.sublime-keymap)(.*)
windowrule= float on, match:title (.*)(Sign In)(.*)
windowrule= float on, match:title (.*)(Bitwarden)(.*)
windowrule= float on, match:title (.*)(PPPPP)(.*)
windowrule= float on, match:title (Select Files)
# windowrule=float,title:(.*)(- mpv)(.*)
windowrule= float on, match:title (Find Directory)
windowrule= float on, match:title Dialog
windowrule= float on, match:title Form
windowrule= fullscreen on, match:title PyMOL
windowrule= float on, match:title PyMOL
# windowrule=stayfocused,title:PyMOL
