[font]
size = 12

[font.normal]
family = "Source Code Pro"
# family = "FiraCode Nerd Font"
style = "Regular"

# [window]
# opacity = 1

[window.padding]
x = 3
y = 5

[selection]
save_to_clipboard = true
